language: php

services:
  - docker

sudo: required

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker pull bcondon/docker_tripal3

script:
  - docker run -it -d --rm --name tripal3 -v "$(pwd)":/modules/tripal_curator statonlab/drupal7
  - sleep 30 #We pause here so drush won't fail
  - docker exec -it tripal drush pm-enable -y tripal_curator
  - docker exec -it tripal bash -c 'cd /var/www/html/sites/all/modules/tripal_curator/ &&composer install && DRUPAL_ROOT="/var/www/html" ./vendor/bin/phpunit'
